import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { OUT } from "./config.ts";
import type { VerifiedIdToken } from "./jose.ts";
import { toHex } from "./b64.ts";

// Must match MAX_SIGNING_INPUT in circuit/src/main.nr.
export const MAX_SIGNING_INPUT = 768;

export async function dumpAll(v: VerifiedIdToken): Promise<string[]> {
  await mkdir(OUT, { recursive: true });

  const written: string[] = [];
  const w = async (name: string, body: string | Uint8Array) => {
    const path = resolve(OUT, name);
    await writeFile(path, body);
    written.push(path);
  };

  await w("jwe.parts.json", JSON.stringify(v.jwe, null, 2));
  await w("jws.parts.json", JSON.stringify(v.jws, null, 2));
  await w("jws.compact.txt", v.jwsCompact);
  await w("jws.header.json", JSON.stringify(v.header, null, 2));
  await w("jws.payload.json", JSON.stringify(v.payload, null, 2));

  await w("signing_input.bin", v.signingInput);
  await w("signing_input.hash.hex", toHex(v.messageHash));

  await w("signature.64.hex", toHex(v.signature64));
  await w("signature.r.hex", toHex(v.r));
  await w("signature.s.hex", toHex(v.s));

  await w("pubkey.x.hex", toHex(v.pubX));
  await w("pubkey.y.hex", toHex(v.pubY));
  await w("issuer_jwk.json", JSON.stringify(v.issuerJwk, null, 2));

  // Raw decoded JWS payload bytes — kept for debugging / TS-side verification.
  await w("payload.bin", v.payloadBytes);

  const paddedSigningInput = padBytes(v.signingInput, MAX_SIGNING_INPUT);
  await w("signing_input.padded.bin", paddedSigningInput);

  // Header base64url length = offset of the '.' separator in signing_input.
  const headerB64Len = v.jws.header.length;
  await w(
    "signing_input.meta.json",
    JSON.stringify(
      {
        signing_input_len: v.signingInput.length,
        header_b64_len: headerB64Len,
        payload_b64_len: v.signingInput.length - headerB64Len - 1,
      },
      null,
      2,
    ),
  );

  await w(
    "Prover.toml",
    makeProverToml(v, paddedSigningInput, headerB64Len),
  );

  return written;
}

function padBytes(bytes: Uint8Array, maxLen: number): Uint8Array {
  if (bytes.length > maxLen) {
    throw new Error(
      `payload length ${bytes.length} > max ${maxLen}. Bump MAX_SIGNING_INPUT.`,
    );
  }
  const out = new Uint8Array(maxLen);
  out.set(bytes, 0);
  return out;
}

function makeProverToml(
  v: VerifiedIdToken,
  paddedSigningInput: Uint8Array,
  headerB64Len: number,
): string {
  return [
    "# Auto-generated by @singpass-zk/rp.",
    "# Drop into ../circuit/Prover.toml and run `nargo execute`.",
    "",
    `pubkey_x = ${bytesToTomlArray(v.pubX)}`,
    `pubkey_y = ${bytesToTomlArray(v.pubY)}`,
    `signature = ${bytesToTomlArray(v.signature64)}`,
    `signing_input = ${bytesToTomlArray(paddedSigningInput)}`,
    `signing_input_len = "${v.signingInput.length}"`,
    `header_b64_len = "${headerB64Len}"`,
    "",
  ].join("\n");
}

function bytesToTomlArray(b: Uint8Array): string {
  const items = Array.from(b).map((x) => `"${x}"`).join(", ");
  return `[${items}]`;
}
