import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { OUT } from "./config.ts";
import type { VerifiedIdToken } from "./jose.ts";
import { toHex } from "./b64.ts";

export async function dumpAll(v: VerifiedIdToken): Promise<string[]> {
  await mkdir(OUT, { recursive: true });

  const written: string[] = [];
  const w = async (name: string, body: string | Uint8Array) => {
    const path = resolve(OUT, name);
    await writeFile(path, body);
    written.push(path);
  };

  await w("jwe.parts.json", JSON.stringify(v.jwe, null, 2));
  await w("jws.parts.json", JSON.stringify(v.jws, null, 2));
  await w("jws.compact.txt", v.jwsCompact);
  await w("jws.header.json", JSON.stringify(v.header, null, 2));
  await w("jws.payload.json", JSON.stringify(v.payload, null, 2));

  await w("signing_input.bin", v.signingInput);
  await w("signing_input.hash.hex", toHex(v.messageHash));

  await w("signature.64.hex", toHex(v.signature64));
  await w("signature.r.hex", toHex(v.r));
  await w("signature.s.hex", toHex(v.s));

  await w("pubkey.x.hex", toHex(v.pubX));
  await w("pubkey.y.hex", toHex(v.pubY));
  await w("issuer_jwk.json", JSON.stringify(v.issuerJwk, null, 2));

  await w("Prover.toml", makeProverToml(v));

  return written;
}

function makeProverToml(v: VerifiedIdToken): string {
  return [
    "# Auto-generated by @singpass-zk/rp.",
    "# Drop into ../circuit/Prover.toml and run `nargo execute`.",
    "",
    `pubkey_x = ${bytesToTomlArray(v.pubX)}`,
    `pubkey_y = ${bytesToTomlArray(v.pubY)}`,
    `message_hash = ${bytesToTomlArray(v.messageHash)}`,
    `signature = ${bytesToTomlArray(v.signature64)}`,
    "",
  ].join("\n");
}

function bytesToTomlArray(b: Uint8Array): string {
  const items = Array.from(b).map((x) => `"${x}"`).join(", ");
  return `[${items}]`;
}
